services:
  # Backend Service
  - type: web
    name: cps-learning-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        value: cps_learning_system
      - key: GROQ_API_KEY
        sync: false
